/* Generated by Yosys 0.60+70 (git sha1 8101c87fa, clang++ 18.1.8 -fPIC -O3) */

(* src = "counter.v:1.1-19.10" *)
module counter(clk, reset, d, si, scan_en, q);
  (* src = "counter.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.9-3.14" *)
  input reset;
  wire reset;
  (* src = "counter.v:4.9-4.10" *)
  input d;
  wire d;
  (* src = "counter.v:5.9-5.11" *)
  input si;
  wire si;
  (* src = "counter.v:6.9-6.16" *)
  input scan_en;
  wire scan_en;
  (* src = "counter.v:7.14-7.15" *)
  output q;
  reg q;
  (* src = "counter.v:10.1-17.4" *)
  wire _0_;
  assign _0_ = scan_en ? si : d;
  (* src = "counter.v:10.1-17.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q <= 1'h0;
    else q <= _0_;
endmodule

(* top =  1  *)
(* src = "counter_top.v:1.1-21.10" *)
module counter_top(clk, reset, scan_in, scan_en, scan_out, q);
  (* src = "counter_top.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "counter_top.v:3.9-3.14" *)
  input reset;
  wire reset;
  (* src = "counter_top.v:4.9-4.16" *)
  input scan_in;
  wire scan_in;
  (* src = "counter_top.v:5.9-5.16" *)
  input scan_en;
  wire scan_en;
  (* src = "counter_top.v:6.10-6.18" *)
  output scan_out;
  wire scan_out;
  (* src = "counter_top.v:7.16-7.17" *)
  output [3:0] q;
  wire [3:0] q;
  wire _0_;
  wire _1_;
  (* src = "counter_top.v:10.12-10.13" *)
  wire [3:0] d;
  assign d[0] = ~q[0];
  assign d[1] = q[1] ^ q[0];
  assign _0_ = ~(q[1] & q[0]);
  assign d[2] = ~(_0_ ^ q[2]);
  assign _1_ = q[2] & ~(_0_);
  assign d[3] = _1_ ^ scan_out;
  (* module_not_derived = 32'd1 *)
  (* src = "counter_top.v:14.9-14.55" *)
  counter ff0 (
    .clk(clk),
    .d(d[0]),
    .q(q[0]),
    .reset(reset),
    .scan_en(scan_en),
    .si(scan_in)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_top.v:15.9-15.55" *)
  counter ff1 (
    .clk(clk),
    .d(d[1]),
    .q(q[1]),
    .reset(reset),
    .scan_en(scan_en),
    .si(q[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_top.v:16.9-16.55" *)
  counter ff2 (
    .clk(clk),
    .d(d[2]),
    .q(q[2]),
    .reset(reset),
    .scan_en(scan_en),
    .si(q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_top.v:17.9-17.55" *)
  counter ff3 (
    .clk(clk),
    .d(d[3]),
    .q(scan_out),
    .reset(reset),
    .scan_en(scan_en),
    .si(q[2])
  );
  assign q[3] = scan_out;
endmodule
