/* Generated by Yosys 0.60+70 (git sha1 8101c87fa, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "addr.v:1.1-7.10" *)
module addr(a, b, c, sum, carry);
  (* src = "addr.v:2.12-2.13" *)
  input a;
  wire a;
  (* src = "addr.v:2.14-2.15" *)
  input b;
  wire b;
  (* src = "addr.v:2.16-2.17" *)
  input c;
  wire c;
  (* src = "addr.v:3.12-3.15" *)
  output sum;
  wire sum;
  (* src = "addr.v:3.16-3.21" *)
  output carry;
  wire carry;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  assign _02_ = b ^ a;
  assign sum = _02_ ^ c;
  assign _03_ = b & a;
  assign _04_ = c & b;
  assign _00_ = _04_ | _03_;
  assign _01_ = c & a;
  assign carry = _01_ | _00_;
endmodule
