
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 23 2026 10:33:20 IST (Jan 23 2026 05:03:20 UTC)

// Verification Directory fv/addr 

module addr(a, b, c, sum, carry);
  input a, b, c;
  output sum, carry;
  wire a, b, c;
  wire sum, carry;
  ADDFX4 g89(.A (b), .B (c), .CI (a), .CO (carry), .S (sum));
endmodule

